apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-tools-pvc
  namespace: coding
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-tools
  namespace: coding
  labels:
    app: coding-tools

spec:
  volumes:
    - name: coding-space
      persistentVolumeClaim:
        claimName: dev-tools-pvc

  containers:
  - name: go-container
    image: golang:1.23
    command: ["sleep", "infinity"]
    workingDir: /workingspace
    volumeMounts:
      - name: coding-space
        mountPath: /workingspace
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  - name: python-container
    image: python:3.11-slim
    command: ["sleep", "infinity"]
    workingDir: /workingspace
    volumeMounts:
      - name: coding-space
        mountPath: /workingspace
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

